[package]
name = "kalmanfilters"
version = "0.1.0"
edition = "2021"

[dependencies]
approx = "0.5.1"
derive_more = { version = "1.0.0", features = ["from", "add","display"]}
nalgebra = "0.33.2"
num-traits = "0.2.19"
